import { ERDProject, Entity, Field } from '../types';

export const generateSQL = (project: ERDProject): string => {
    let sql = `-- SQL Generated by ERD.PRO Designer\n`;
    sql += `-- Project: ${project.metadata.name}\n`;
    sql += `-- Created: ${new Date(project.metadata.created).toLocaleString()}\n`;
    sql += `-- Modified: ${new Date(project.metadata.modified).toLocaleString()}\n\n`;

    // 1. Create Tables
    project.entities.forEach(entity => {
        sql += `CREATE TABLE ${entity.name} (\n`;

        const fieldLines = entity.fields.map((field: Field, index) => {
            let line = `    ${field.name} ${field.type}`;

            if (field.length) line += `(${field.length})`;
            else if (field.precision && field.scale) line += `(${field.precision}, ${field.scale})`;

            if (field.constraints.notNull) line += ` NOT NULL`;
            if (field.constraints.primaryKey) line += ` PRIMARY KEY`;
            if (field.constraints.unique) line += ` UNIQUE`;
            if (field.constraints.autoIncrement) {
                // Heuristic: serial for postgres, auto_increment for mysql
                line += ` SERIAL`;
            }
            if (field.constraints.defaultValue !== undefined) {
                const val = typeof field.constraints.defaultValue === 'string'
                    ? `'${field.constraints.defaultValue}'`
                    : field.constraints.defaultValue;
                line += ` DEFAULT ${val}`;
            }

            return line;
        });

        sql += fieldLines.join(',\n');
        sql += `\n);\n\n`;
    });

    // 2. Add Foreign Keys (Alter Tables)
    project.relationships.forEach(rel => {
        const sourceEntity = project.entities.find(e => e.id === rel.source.entityId);
        const targetEntity = project.entities.find(e => e.id === rel.target.entityId);
        const sourceField = sourceEntity?.fields.find(f => f.id === rel.source.fieldId);
        const targetField = targetEntity?.fields.find(f => f.id === rel.target.fieldId);

        if (sourceEntity && targetEntity && sourceField && targetField) {
            sql += `ALTER TABLE ${targetEntity.name}\n`;
            sql += `ADD CONSTRAINT fk_${targetEntity.name}_${sourceEntity.name}\n`;
            sql += `FOREIGN KEY (${targetField.name}) REFERENCES ${sourceEntity.name}(${sourceField.name});\n\n`;
        }
    });

    return sql;
};
